services:
  postgres:
    image: postgres:latest
    container_name: etfbook_dev_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: commando
      POSTGRES_DB: etfbook
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: etfbook_dev_pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin-data:/var/lib/pgadmin




volumes:
  postgres_data:
  pgadmin-data: